name: AMP-modification
channels:
  - conda-forge
  - pytorch
dependencies:
  - conda-forge::python=3.8
  - conda-forge::pip
  - pytorch::pytorch=2.0.1
  - pip:
      - pandas==1.3.4
      - numpy==1.22.4
      - transformers==4.27.4
      - peft==0.3.0
      - scikit-learn==1.0.1
      - umap-learn==0.5.3
      - plotly==5.15.0
      - focal_loss_torch==0.1.2
      - tqdm==4.62.3